---
name: Data-Leaf-Walker
version: 0.20
author:
  - 'Dan Boorstein <danboo@cpan.org>'
abstract: Walk the leaves of arbitrarily deep nested data structures.
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/danboo/perl-data-leaf-walker/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Data::Leaf::Walker:
    file: lib/Data/Leaf/Walker.pm
    version: 0.20
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
